language: ruby
rvm:
- 2.4.1
services:
  - postgresql
before_script:
  - psql -c 'create database praybook_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - ./bin/webpack
cache: yarn
