language: ruby
rvm:
- 2.4.1
services:
  - postgresql
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - psql -c 'create database praybook_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - yarn
  - ../bin/webpack
